name: CI/CD for Vue.js on AWS

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

#      - name: Build Vue.js app
#        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance
        run: |
          echo "$AWS_SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem     
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@18.139.160.58 "cd Frontend/ProjectPractice && git pull origin frontend && chmod +x deploy-script.sh && ./deploy-script.sh"
        env:
          AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}



